baseURL = "http://ravishankars.com/"
languageCode = "en-us"
title = "Ravishankar Sivasubramaniam"
theme = "minimal"
googleAnalytics = "UA-119195186-1"

[params]
    author = "Ravishankar Sivasubramaniam"
    description = "Data Engineering | Machine Learning | Python"
    Location = "Chicago, IL"
    githubUsername = "ravishan16"
    accent = "black"
    showBorder = false
    backgroundColor = "white"
    font = "Roboto" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "Atelier Forest Dark"
    highlightLanguages = ["Python", "JavaScript", "JSON", "SQL"]
    profilePic = "images/profile.JPG"
    copyright = "Copyright &#xA9; 2018 Ravishankar Sivasubramaniam. All Rights Reserved. Powered by [Hugo](https://gohugo.io) and [Minimal](https://github.com/calintat/minimal)"

[[menu.main]]
    url = "/"
    name = "Ravi"
    weight = 1


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:contact@ravishankars.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/ravishan16/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://flipboard.com/@ravishan/padikka-0cu079foz"
    name = "fab fa-flipboard"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/ravibi/"
    name = "fab fa-linkedin"
    weight = 4